version: '3.4'

services:
  cinematoonweb.mvc:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
       - "44386:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
  cinematoon.cinemabooking.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "44347:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
  cinematoon.identityserver:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "44329:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
  cinematoon.movies.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development  
    ports:
      - "4455:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro    
  cinematoon.fakepaymentservice.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "44377:80"
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:C:\Users\ContainerUser\AppData\Roaming\Microsoft\UserSecrets:ro
  cinematoon.theaters.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
    ports:
      - "44378:80"

networks:
  default:
    external:
      name: nat





